WebsiteUI/Models/PartialViewModels/EditProductImageViewModel.cs
namespace WebsiteUI.Models.PartialViewModels
{
	public class EditProductImageViewModel
	{
		public ImageModel ImageModel { get; set; }
		public ProductModel ProductModel { get; set; }
	}
}

WebsiteUI/Controllers/AdminController.cs
using Business.Abstract;
using Entities;
using Entities.UserEntities.SiteUser;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using WebsiteUI.Extensions;
using WebsiteUI.FunctionsLibrary;
using WebsiteUI.Models;
using WebsiteUI.Models.OtherClasses;
using WebsiteUI.Models.PartialViewModels;
using WebsiteUI.ViewModels;
using WebsiteUI.ViewModels.AdminViewModels;

namespace WebsiteUI.Controllers
{
    /*
     TODO
    - Need to implement a system that holds necessary data while deleting objects.
    - Need to implement a system that settles popular products.
     */

    public class AdminController : Controller
    {
        //Configuration Parameters
        private IProductService _productService;
        private ICategoryService _categoryService;
        private IImageService _imageService;

        private RoleManager<IdentityRole> _roleManager;
        private UserManager<SiteUser> _userManager;

        private AssistantFunctions helperLib = new AssistantFunctions();
        public AdminController(IProductService productService, ICategoryService categoryService, IImageService imageService,
            UserManager<SiteUser> userManager, RoleManager<IdentityRole> roleManager)
        {
            _productService = productService;
            _categoryService = categoryService;
            _imageService = imageService;
            _userManager = userManager;
            _roleManager = roleManager;
        }
        //General Parameters
        private int pageSize = 2;
        private int PopularProductSelectionRange = 50;

        public IActionResult Index()
        {
            return View();
        }

        //Product Actions

        public async Task<IActionResult> ProductList()
        {
            var products = await _productService.GetAllAsync();
            ProductListViewModel listModel = new ProductListViewModel();

            foreach (var product in products)
            {
                var pModel = helperLib.CreateProductModel(product);
                pModel.ImageModels = helperLib.CreateImageModels(_productService.GetProductImages(pModel.Id));
                listModel.ProductModels.Add(pModel);
            }

            return View(listModel);
        }

        [HttpGet]
        public async Task<IActionResult> CreateProduct()
        {
            CreateProductViewModel viewModel = new CreateProductViewModel();
            var categories = await _categoryService.GetAllAsync();

            foreach (var category in categories)
            {
                viewModel.CategoryModels.Add(helperLib.CreateCategoryModel(category));
            }

            return View(viewModel);
        }

        [HttpPost]
        public async Task<IActionResult> CreateProduct(CreateProductViewModel viewModel, int[] categoryIds)
        {
            List<Image> imagesToAdd = new List<Image>();

            if (!ModelState.IsValid)
            {
                return View(viewModel);
            }

            Product entity = helperLib.CreateProduct(viewModel.ProductModel);

            entity.SetStockState(viewModel.ProductModel.StockStateNumber);
            entity.IsApproved = true;

            if (viewModel.ImageFiles.Count > 0)
            {
                bool isFirst = true;

                foreach (var file in viewModel.ImageFiles)
                {
                    string extension = Path.GetExtension(file.FileName).ToLower();
                    string generatedName = string.Format($"{Guid.NewGuid()}{extension}");

                    string path = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot\\img", generatedName);

                    using (FileStream stream = new FileStream(path, FileMode.Create))
                    {
                        await file.CopyToAsync(stream);
                    }

                    if (isFirst)
                    {
                        var image = helperLib.CreateImage(new ImageModel
                        {
                            Url = generatedName,
                            IsMainImageOfProduct = true,
                            IsHomeDisplay = false
                        });
                        _imageService.Create(image);
                        imagesToAdd.Add(image);
                        entity.MainImageUrl = image.Url;
                    }
                    else
                    {
                        var image = helperLib.CreateImage(new ImageModel
                        {
                            Url = generatedName,
                            IsMainImageOfProduct = false,
                            IsHomeDisplay = false
                        });
                        _imageService.Create(image);
                        imagesToAdd.Add(image);
                    }
                }
            }


            if (_productService.Create(entity))
            {
                _productService.AddCategories(entity.Id, categoryIds);
                foreach (var image in imagesToAdd)
                {
                    _productService.AddImage(entity.Id, image.Id);
                }
                CreateMessage("yeni ürün eklendi.", "success", "Başarılı");
                return RedirectToAction("ProductList");
            }
            else
            {
                CreateMessage(_productService.ErrorMessage, "danger", "Ürün Oluştururken Hata");
                return View(viewModel);
            }
        }

        [HttpGet]
        public async Task<IActionResult> EditProduct(int productId)
        {
            if (productId == null)
            {
                return NotFound();
            }

            Product entity = _productService.GetById(productId);

            if (entity == null)
            {
                return NotFound();
            }

            ProductModel model = helperLib.CreateProductModel(entity);
            model.ImageModels = helperLib.CreateImageModels(_productService.GetProductImages(productId));
            model.SelectedCategories = _productService.GetCategoriesOfProduct(entity.Id);
            ViewBag.Categories = await _categoryService.GetAllAsync();
            model.Id = productId;

            EditProductViewModel viewModel = new EditProductViewModel();
            viewModel.ProductModel = model;

            return View(viewModel);
        }

        [HttpPost]
        public async Task<IActionResult> EditProduct(EditProductViewModel model, int[] categoryIds)
        {

            Product entity = _productService.GetById(model.ProductModel.Id);
            ProductModel pModel = model.ProductModel;
            List<Image> imagesToAdd = new List<Image>();

            if (entity == null)
            {
                return NotFound();
            }
            entity.Name = pModel.Name;
            entity.ProductUrl = helperLib.GenerateUrl(entity.Name);
            entity.CardDescription = pModel.CardDescription;
            entity.Description = pModel.Description;
            //entity.BaseDolarPrice = pModel.BaseDolarPrice;
            entity.BasePrice = pModel.BasePrice;
            entity.SalePrice = pModel.SalePrice;
            entity.Quantity = pModel.Quantity;
            entity.IsApproved = pModel.IsApproved;
            entity.IsSuggested = pModel.IsHomeDisplay;
            entity.IsAltered = true;
            entity.SetStockState(pModel.StockStateNumber);
            entity.SetBasePriceType(pModel.BasePriceTypeNumber);
            if (model.ImageFiles.Count > 0)
            {
                bool isFirst = true;

                foreach (var file in model.ImageFiles)
                {
                    string extension = Path.GetExtension(file.FileName).ToLower();
                    string generatedName = string.Format($"{Guid.NewGuid()}{extension}");

                    string path = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot\\img", generatedName);

                    using (FileStream stream = new FileStream(path, FileMode.Create))
                    {
                        await file.CopyToAsync(stream);
                    }

                    if (isFirst)
                    {
                        var image = helperLib.CreateImage(new ImageModel
                        {
                            Url = generatedName,
                            IsMainImageOfProduct = true,
                            IsHomeDisplay = false
                        });
                        entity.MainImageUrl = image.Url;
                        _imageService.Create(image);
                        imagesToAdd.Add(image);
                    }
                    else
                    {
                        var image = helperLib.CreateImage(new ImageModel
                        {
                            Url = generatedName,
                            IsMainImageOfProduct = false,
                            IsHomeDisplay = false
                        });
                        _imageService.Create(image);
                        imagesToAdd.Add(image);
                    }
                }
            }

            if (_productService.Update(entity, categoryIds))
            {
                foreach (var image in imagesToAdd)
                {
                    _productService.AddImage(entity.Id, image.Id);
                }
                CreateMessage("düzenleme başarılı", "success", "Ürün Başarıyla Düzenlendi");
                return RedirectToAction("ProductList");
            }
            else
            {
                CreateMessage("error mesaj", "danger", "Ürün Düzenlerken Hata");
                return View(model);
            }
            return View(model);
        }

        public IActionResult RemoveImageFromProduct(int productId, string imageUrl)
        {//IMPLEMENT
            _imageService.RemoveImageFromProduct(productId, imageUrl);
            return Redirect("~/admin/editproduct/" + productId);
        }

WebsiteUI/Controllers/CartController.cs
using Microsoft.AspNetCore.Mvc;

namespace WebsiteUI.Controllers
{
    public class CartController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

WebsiteUI/Controllers/ProductController.cs
using Business.Abstract;
using Entities;
using Microsoft.AspNetCore.Mvc;
using WebsiteUI.FunctionsLibrary;
using WebsiteUI.Models;

namespace WebsiteUI.Controllers
{
    /*
     TODO
    - A system to take care of stock state situations. DON'T CHANGE STOCK STATE IN CASE OF ON ORDER
    - product list listeleme işlemleri
     */

    public class ProductController : Controller
    {

        private IProductService _productService;
        private ICategoryService _categoryService;
        private AssistantFunctions helperLib = new AssistantFunctions();

        private int pageSize = 24;

        public ProductController(IProductService productService, ICategoryService categoryService)
        {
            _productService = productService;
            _categoryService = categoryService;
        }

        public IActionResult Index()
        {
            return View();
        }

        public async Task<IActionResult> List(string categoryUrl, int page = 1, int sortingIndex = 4)
        {
            ProductListViewModel listModel = new ProductListViewModel()
            {
                PageInfo = new PageInfo()
                {
                    TotalItems = _productService.GetCountByCategory(categoryUrl),
                    CurrentPage = page,
                    ItemsPerPage = pageSize,
                    CurrentCategoryUrl = categoryUrl
                },
                CurrentAction = "List"
            };
            var products = await _productService.GetProductsByCategoryAsync(categoryUrl, pageSize, page, false);
            var categories = await _categoryService.GetAllAsync();

            foreach (Product product in products)
            {
                ProductModel productModel = helperLib.CreateProductModel(product);
                productModel.ImageModels.AddRange(helperLib.CreateImageModels(_productService.GetProductImages(productModel.Id)));

                listModel.ProductModels.Add(productModel);
            }

            if (!string.IsNullOrEmpty(categoryUrl))
            {
                _categoryService.IncreaseCategoryViewCount(categoryUrl);
            }
            
            if(sortingIndex != -1)
            {
                listModel.ProductModels = helperLib.OrderProductModels(listModel.ProductModels, sortingIndex);
            }

            return View(listModel);
        }

        public IActionResult Details(string productUrl)
        {
            string refactoredProductUrl = helperLib.GenerateUrl(productUrl);

            if (refactoredProductUrl == null)
            {
                Console.WriteLine("NOT FOUND NOT FOUND NOT FOUND");
                return NotFound();
            }

            Product product = _productService.GetProductDetails(refactoredProductUrl);

            if (product == null)
            {
                Console.WriteLine("PRODUCT == NULL");
                return NotFound();
            }

            ProductModel model = helperLib.CreateProductModel(product);

            model.SelectedCategories = product.ProductCategories.Select(pc => pc.Category).ToList();
            var images = product.ProductImages.Select(pi => pi.Image).ToList();

            foreach (var image in images)
            {
                model.ImageModels.Add(helperLib.CreateImageModel(image));
            }

            _productService.IncreaseProductViewCount(refactoredProductUrl);

            return View(model);
        }

        public async Task<IActionResult> Search(string searchString, int sortingIndex = -1)
        {
            ProductListViewModel listModel = new ProductListViewModel()
            {
                PageInfo = new PageInfo()
                {
                    CurrentPage = 1,
                    ItemsPerPage = pageSize
                },
                CurrentAction = "Search",
                SearchString = searchString
            };
            var products = await _productService.GetSearchResultsAsync(searchString);
            listModel.PageInfo.TotalItems = products.Count;
            foreach (var product in products)
            {
                listModel.ProductModels.Add(helperLib.CreateProductModel(product));
            }

            if (sortingIndex != -1)
            {
                listModel.ProductModels = helperLib.OrderProductModels(listModel.ProductModels, sortingIndex);
            }

            return View("List", listModel);
        }
    }
}


// Sort action prototype

/*public async Task<IActionResult> Sort(int sortingIndex, ProductListViewModel viewModel)
        {
            Console.WriteLine("In Sort Action");

            ProductListViewModel listModel = new ProductListViewModel()
            {
                PageInfo = new PageInfo()
                {
                    CurrentPage = 1,
                    ItemsPerPage = pageSize
                }
            };

            if(viewModel.ProductModels.Count > 0)
            {
                var orderedProducts = helperLib.OrderProductModels(viewModel.ProductModels, sortingIndex);
                listModel.ProductModels.AddRange(orderedProducts);
            }
            else
            {
                var products = await _productService.GetSortedProducts(sortingIndex);

                foreach (var product in products)
                {
                    listModel.ProductModels.Add(helperLib.CreateProductModel(product));
                }
            }

            

            return View("List", listModel);
        }*/

WebsiteUI/Views/Shared/_DangerMessage.cshtml
@model string

<div class="row">
	<div class="col-md-12">
		<div class="alert alert-danger">
			@Model
		</div>
	</div>
</div>

WebsiteUI/Views/Shared/_EditProductImage.cshtml
@using WebsiteUI.Models.PartialViewModels
@model EditProductImageViewModel

<div class="card mb-2 light-background">
	<div style="width: 30px; height: 30px; align-self:end;">
		<a asp-controller="Admin" asp-action="RemoveImageFromProduct" asp-route-productId="@Model.ProductModel.Id" asp-route-imageUrl="@Model.ImageModel.Url" class="btn">
			<i class="fa-solid fa-x" style="background-color: red;"></i>
		</a>
	</div>
	<img class="card-img-top" src="~/img/@Model.ImageModel.Url" />
</div>

WebsiteUI/Views/Shared/_Footer.cshtml
<div class="footer p-1">
	&copy; 2022 - WebsiteUI - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
</div>

WebsiteUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<title>Çınarmak Bahçe Makineleri</title>
	<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
	<link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
	<link rel="stylesheet" href="~/WebsiteUI.styles.css" asp-append-version="true" />
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.0/css/all.min.css" integrity="sha512-xh6O/CkQoPOWDdYTDqeRdPCVd1SpvCA9XXcUnZS2FmJNp1coAFzvtCN9BmamE+4aHK8yyUHUSCcJHgXloTyT2A==" crossorigin="anonymous" referrerpolicy="no-referrer" />
	@await RenderSectionAsync("Css", required: false)
</head>
<body>
	<header>
		@await Html.PartialAsync("_Navbar")
	</header>
	<div class="m-2">
		<main role="main" class="pb-3">
			@RenderBody()
		</main>
	</div>


	<footer class="border-top footer text-muted">
		@await Html.PartialAsync("_Footer")
	</footer>
	<script src="~/lib/jquery/dist/jquery.min.js"></script>
	<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
	<script src="~/js/site.js" asp-append-version="true"></script>
	@await RenderSectionAsync("Scripts", required: false)
</body>
</html>

WebsiteUI/Views/Shared/_Navbar.cshtml
@using Entities.UserEntities.SiteUser
<nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
	<div class="container-fluid">
		<a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">WebsiteUI</a>
		<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
				aria-expanded="false" aria-label="Toggle navigation">
			<span class="navbar-toggler-icon"></span>
		</button>
		<div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
			<ul class="navbar-nav flex-grow-1">
				<li class="nav-item">
					<a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Ana Sayfa</a>
				</li>
				<li class="nav-item">
					<a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
				</li>
				<li class="nav-item">
					<a class="nav-link text-dark" asp-area="" asp-controller="Product" asp-action="List">Ürünler</a>
				</li>
			</ul>
			<div class="nav-item d-flex justify-content-end">
				<form asp-controller="Product" asp-action="Search" class="d-flex">
					<input class="form-control me-2" type="search" placeholder="Ürün Ara" aria-label="Search" name="searchString">
					<button class="btn btn-outline-success" type="submit">Ara</button>
				</form>
				<ul class="navbar-nav flex-grow-1">
					@if (User.Identity.IsAuthenticated)
					{
						Console.WriteLine("in user.identity.isauthenticated");
						<li class="nav-item">
							<a class="nav-link text-dark" asp-area="" asp-controller="Cart" asp-action="Index">Sepet</a>
						</li>
						<li class="nav-item">
							<a class="nav-link text-dark" asp-area="" asp-controller="Order" asp-action="GetOrders">Siparişler</a>
						</li>
						@if (User.IsInRole("Admin"))
						{
							Console.WriteLine("user is an admin");
							<li class="nav-item">
								<div class="dropdown">
									<button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenu2" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
										Admin Sayfaları
									</button>
									<div class="dropdown-menu" aria-labelledby="dropdownMenu2">
										<a class="dropdown-item" asp-controller="Admin" asp-action="AdminPage">Admin Ana Sayfası</a>
										<a class="dropdown-item" asp-controller="Admin" asp-action="ProductList">Ürün Ayarları</a>
										<a class="dropdown-item" asp-controller="Admin" asp-action="CategoryList">Kategori Ayarları</a>
										<a class="dropdown-item" asp-controller="Admin" asp-action="RoleList">Rol Listesi</a>
										<a class="dropdown-item" asp-controller="Admin" asp-action="UserList">Kullanıcı Listesi</a>
									</div>
								</div>
							</li>
						}

						<li class="nav-item">
							<a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Manage">@User.Identity.Name</a>
						</li>
						<li class="nav-item">
							<button class="nav-item btn text-dark" type="button" data-bs-toggle="modal" data-bs-target="#logoutModal">Çıkış Yap</button>
						</li>

						<!-- Logout Modal -->
						<div class="modal fade" id="logoutModal" tabindex="-1" aria-labelledby="logoutModalLabel" aria-hidden="true">
							<div class="modal-dialog">
								<div class="modal-content">
									<div class="modal-header">
										<h5 class="modal-title" id="logoutModalLabel">Çıkış</h5>
										<button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
									</div>
									<div class="modal-body">
										<p>Hesabınızdan çıkış yapmak istediğinize emin misiniz?</p>
									</div>
									<div class="modal-footer">
										<button type="button" class="btn btn-secondary" data-bs-dismiss="modal">İptal</button>
										<a asp-controller="Account" asp-action="Logout" class="btn btn-danger">Çıkış Yap</a>
									</div>
								</div>
							</div>
						</div>
					}
					else
					{
						Console.WriteLine("in user.identity.notauthenticated");
						Console.WriteLine(User.Identity.Name + "heyo");
						<li class="nav-item">
							<a class="nav-link text-dark" asp-controller="Account" asp-action="Login">Giriş Yap</a>
						</li>
						<li class="nav-item">
							<a class="nav-link text-dark" asp-controller="Account" asp-action="Register">Kayıt Ol</a>
						</li>
					}
				</ul>
			</div>
		</div>
	</div>
</nav>

WebsiteUI/Views/Shared/_NoProduct.cshtml
<div class="row">
	<div class="col-md-12">
		<div class="alert alert-danger">
			Aranan kriterlere ait ürün bulunmamaktadır.
		</div>
	</div>
</div>

WebsiteUI/Views/Shared/_Product.cshtml
@model ProductModel

@{
	Console.WriteLine("heyyy");
	Console.WriteLine(Model.ImageModels.Count);
	ImageModel mainImage = new ImageModel();
	foreach (var image in Model.ImageModels)
	{
		if (image.IsMainImageOfProduct)
		{
			mainImage = image;
			break;
		}
	}

	if(mainImage == null)
	{
		mainImage = Model.ImageModels.First();
	}
}

<div class="card mb-2 very-light-background">
	<img class="card-img-top" src="~/img/@Model.MainImageUrl" />
	<div class="card-body">
		<h5 class="card-title">@Model.Name</h5>
		<small class="text-muted">
			<i class="fas fa-lira-sign"></i>@Model.SalePrice
		</small>
		<p class="card-text">@Model.CardDescription</p>
		<div class="card-footer text-center">
			<a asp-controller="Product" asp-action="Details" asp-route-productUrl="@Model.ProductUrl" class="btn btn-primary btn-sm">İncele</a>
			<p>@Model.StockStateNumber</p>

			@*@if (User.Identity.IsAuthenticated)
			{
			<form asp-controller="Cart" asp-action="AddToCart" method="post" style="display: inline;">
			<input type="hidden" name="productId" value="@Model.ProductId">
			<input type="hidden" name="quantity" value="1">
			<button type="submit" class="btn btn-primary btn-sm">Sepete Ekle</button>
			</form>
			}*@
		</div>
	</div>
</div>

WebsiteUI/Views/Shared/_Search.cshtml
<div class="card mt-3">
	<div class="card-header">
		<h5>Search</h5>
	</div>
	<div class="card-body">
		<form asp-controller="Product" asp-action="Search">
			<div class="form-group">
				<input name="searchString" type="text" class="form-control mr-2" placeholder="Search" />
			</div>
			<div class="form-group d-grid gap-1">
				<button type="submit" class="btn btn-danger btn mt-2">Search</button>
			</div>
		</form>
	</div>
</div>