WebsiteUI/Controllers/CartController.cs
using Microsoft.AspNetCore.Mvc;

namespace WebsiteUI.Controllers
{
    public class CartController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

WebsiteUI/Controllers/ProductController.cs
using Business.Abstract;
using Entities;
using Microsoft.AspNetCore.Mvc;
using WebsiteUI.FunctionsLibrary;
using WebsiteUI.Models;

namespace WebsiteUI.Controllers
{
    /*
     TODO
    - A system to take care of stock state situations. DON'T CHANGE STOCK STATE IN CASE OF ON ORDER
    - product list listeleme işlemleri
     */

    public class ProductController : Controller
    {

        private IProductService _productService;
        private ICategoryService _categoryService;
        private AssistantFunctions helperLib = new AssistantFunctions();

        private int pageSize = 24;

        public ProductController(IProductService productService, ICategoryService categoryService)
        {
            _productService = productService;
            _categoryService = categoryService;
        }

        public IActionResult Index()
        {
            return View();
        }

        public async Task<IActionResult> List(string categoryUrl, int page = 1, int sortingIndex = 4)
        {
            ProductListViewModel listModel = new ProductListViewModel()
            {
                PageInfo = new PageInfo()
                {
                    TotalItems = _productService.GetCountByCategory(categoryUrl),
                    CurrentPage = page,
                    ItemsPerPage = pageSize,
                    CurrentCategoryUrl = categoryUrl
                },
                CurrentAction = "List"
            };
            var products = await _productService.GetProductsByCategoryAsync(categoryUrl, pageSize, page, false);
            var categories = await _categoryService.GetAllAsync();

            foreach (Product product in products)
            {
                ProductModel productModel = helperLib.CreateProductModel(product);
                productModel.ImageModels.AddRange(helperLib.CreateImageModels(_productService.GetProductImages(productModel.Id)));

                listModel.ProductModels.Add(productModel);
            }

            if (!string.IsNullOrEmpty(categoryUrl))
            {
                _categoryService.IncreaseCategoryViewCount(categoryUrl);
            }
            
            if(sortingIndex != -1)
            {
                listModel.ProductModels = helperLib.OrderProductModels(listModel.ProductModels, sortingIndex);
            }

            return View(listModel);
        }

        public IActionResult Details(string productUrl)
        {
            string refactoredProductUrl = helperLib.GenerateUrl(productUrl);

            if (refactoredProductUrl == null)
            {
                Console.WriteLine("NOT FOUND NOT FOUND NOT FOUND");
                return NotFound();
            }

            Product product = _productService.GetProductDetails(refactoredProductUrl);

            if (product == null)
            {
                Console.WriteLine("PRODUCT == NULL");
                return NotFound();
            }

            ProductModel model = helperLib.CreateProductModel(product);

            model.SelectedCategories = product.ProductCategories.Select(pc => pc.Category).ToList();
            var images = product.ProductImages.Select(pi => pi.Image).ToList();

            foreach (var image in images)
            {
                model.ImageModels.Add(helperLib.CreateImageModel(image));
            }

            _productService.IncreaseProductViewCount(refactoredProductUrl);

            return View(model);
        }

        public async Task<IActionResult> Search(string searchString, int sortingIndex = -1)
        {
            ProductListViewModel listModel = new ProductListViewModel()
            {
                PageInfo = new PageInfo()
                {
                    CurrentPage = 1,
                    ItemsPerPage = pageSize
                },
                CurrentAction = "Search",
                SearchString = searchString
            };
            var products = await _productService.GetSearchResultsAsync(searchString);
            listModel.PageInfo.TotalItems = products.Count;
            foreach (var product in products)
            {
                listModel.ProductModels.Add(helperLib.CreateProductModel(product));
            }

            if (sortingIndex != -1)
            {
                listModel.ProductModels = helperLib.OrderProductModels(listModel.ProductModels, sortingIndex);
            }

            return View("List", listModel);
        }
    }
}


// Sort action prototype

/*public async Task<IActionResult> Sort(int sortingIndex, ProductListViewModel viewModel)
        {
            Console.WriteLine("In Sort Action");

            ProductListViewModel listModel = new ProductListViewModel()
            {
                PageInfo = new PageInfo()
                {
                    CurrentPage = 1,
                    ItemsPerPage = pageSize
                }
            };

            if(viewModel.ProductModels.Count > 0)
            {
                var orderedProducts = helperLib.OrderProductModels(viewModel.ProductModels, sortingIndex);
                listModel.ProductModels.AddRange(orderedProducts);
            }
            else
            {
                var products = await _productService.GetSortedProducts(sortingIndex);

                foreach (var product in products)
                {
                    listModel.ProductModels.Add(helperLib.CreateProductModel(product));
                }
            }

            

            return View("List", listModel);
        }*/

WebsiteUI/ViewComponents/CategoriesViewComponent.cs
using Business.Abstract;
using Microsoft.AspNetCore.Mvc;
using WebsiteUI.FunctionsLibrary;
using WebsiteUI.Models;

namespace WebsiteUI.ViewComponents
{
    public class CategoriesViewComponent : ViewComponent
    {
        private ICategoryService _categoryService;

        private AssistantFunctions helperLib = new AssistantFunctions();

        public CategoriesViewComponent(ICategoryService categoryService)
        {
            _categoryService = categoryService;
        }
        public async Task<IViewComponentResult> InvokeAsync()
        {
            if (RouteData.Values["category"] != null)
            {
                ViewBag.SelectedCategory = RouteData?.Values["category"];
            }
            var categories = await _categoryService.GetAllAsync();
            var listModel = new CategoryListModel();

            foreach (var category in categories)
            {
                listModel.categoryModels.Add(helperLib.CreateCategoryModel(category));
            }
            return View(listModel);
        }
    }
}

WebsiteUI/Views/Product/Details.cshtml
@model ProductModel

@{
	ImageModel mainImage = null;
	List<ImageModel> otherImages = new List<ImageModel>();
	bool found = false;
	foreach (var image in Model.ImageModels)
	{
		if (image.IsMainImageOfProduct && !found)
		{
			mainImage = image;
			found = true;
		}
		else
		{
			otherImages.Add(image);
		}
	}
	if (!found)
	{
		mainImage = otherImages.First();
		otherImages.Remove(mainImage);
	}
}

<div class="card mb-3">
	<div class="card-body">
		<div class="row no-gutters">
			<div class="col-md-3">
				@{
					<div class="row">
						<img src="~/img/@mainImage.Url" class="img-fluid img-details" id="mainImage" onclick="PopImg(this.src);">
						<div id="modal" class="siteModal">
							<span class="close" onclick="CloseImg();">&times;</span>
							<img class="siteModal-content" id="modalImage">
						</div>
					</div>
					<div class="row mt-2">
						@{
							string imgId = "";
							int imgCount = 1;
							foreach (var image in otherImages)
							{
								imgId = "img" + imgCount.ToString();
								<div class="col-4">
									<img src="~/img/@image.Url" class="img-fluid img-details" id="@imgId" onclick="PopImg(this.src);">
									<span class="close" onclick="CloseImg();">&times;</span>
								</div>
								imgCount += 1;
							}
						}
					</div>
				}
			</div>
			<div class="col-md-9">
				<h1 class="mb-3 card-title">@Model.Name</h1> <hr />
				@foreach (Category category in Model.SelectedCategories)
				{
					<a asp-controller="Shop" asp-action="List" asp-route-category="@category.CategoryUrl" class="btn btn-link p-0 mb-3">@category.Name</a>
				}
				<div class="card-text">
					<h4 class="text-primary mb-3">
						<i class="fas fa-lira-sign"></i>
						@Model.SalePrice
					</h4>
				</div>

				<form asp-controller="Cart" asp-action="AddToCart" method="post" class="form-inline">
					<input type="hidden" name="productId" value="@Model.ProductUrl">
					<div class="input-group mb-3">
						<input type="number" name="quantity" value="1" class="form-control" min="1" step="1" style="width: 100px;">
						<div class="input-group-append">
							<button type="submit" class="btn btn-primary">
								<i class="fa-solid fa-cart-shopping">Add to Cart</i>
							</button>
						</div>
					</div>
				</form>

				<button type="submit" class="btn btn-success btn-lg">Add to Card</button>
			</div>
		</div>
		<div class="row">
			<div class="col-md-12">
				<p class="p-3">@Html.Raw(Model.Description)</p>
			</div>
		</div>
	</div>
</div>

<script>
	var span = document.getElementsByClassName("close")[0];
	var modalImg = document.getElementById("modalImage");
	var modal = document.getElementById("modal");

	function PopImg(src) {
		modal.style.display = "block";
		modalImg.src = src;
	}

	function CloseImg() {
		modal.style.display = "none";
	}
</script>

WebsiteUI/Views/Product/List.cshtml
@model ProductListViewModel
@{
	ViewData["Title"] = "Ürünler";
	List<ProductModel> products = Model.ProductModels;
}

<div class="row m-2">
	<div class="col-md-2 border-end border-secondary">
		@await Component.InvokeAsync("Categories")

		<div class="dropdown mt-2">
			<button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenu2" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
				Sıralama Seçenekleri
			</button>
			<div class="dropdown-menu" aria-labelledby="dropdownMenu2">
				<a asp-controller="Product" asp-action="@Model.CurrentAction" asp-route-searchString = "@Model.SearchString" asp-route-sortingIndex="1" class="dropdown-item" type="button">Alfabetik</a>
				<a asp-controller="Product" asp-action="@Model.CurrentAction" asp-route-searchString = "@Model.SearchString" asp-route-sortingIndex="4" class="dropdown-item" type="button">Popülerliğe Göre</a>
				<a asp-controller="Product" asp-action="@Model.CurrentAction" asp-route-searchString = "@Model.SearchString" asp-route-sortingIndex="2" class="dropdown-item" type="button">Fiyata Göre Artan</a>
				<a asp-controller="Product" asp-action="@Model.CurrentAction" asp-route-searchString = "@Model.SearchString" asp-route-sortingIndex="3" class="dropdown-item" type="button">Fiyata Göre Azalan</a>
			</div>
		</div>
		<partial name="_Search" />

	</div>
	@if (@Model.ProductModels.Count == 0)
	{
		<div class="col-md-10">
			<div class="row">
				@await Html.PartialAsync("_NoProduct")
			</div>
		</div>
	}
	else
	{
		<div class="col-md-10">
			<div class="row">
				@foreach (var product in products)
				{
					<div class="col-lg-2 col-md-3 col-sm-6">
						@await Html.PartialAsync("_Product", product)
					</div>
				}
			</div>
		</div>
	}

</div>

<div class="row">
	<div class="col">
		<nav aria-label="Page navigation">
			<ul class="paginatio n n">
				@for (int i = 0; i < Model.PageInfo.TotalPages(); i++)
				{
					if (!string.IsNullOrEmpty(Model.PageInfo.CurrentCategoryUrl))
					{
						if (Model.PageInfo.CurrentPage == (i + 1))
						{
							<li class="page-item active">
								<a class="page-link" href="/product/list/@Model.PageInfo.CurrentCategoryUrl?page=@(i+1)">@(i+1)</a>
							</li>
						}
						else
						{
							<li class="page-item">
								<a class="page-link" href="/product/list/@Model.PageInfo.CurrentCategoryUrl?page=@(i+1)">@(i+1)</a>
							</li>
						}
					}
					else
					{
						if (Model.PageInfo.CurrentPage == (i + 1))
						{
							<li class="page-item active">
								<a class="page-link" href="/product/list/?page=@(i+1)">@(i+1)</a>
							</li>
						}
						else
						{
							<li class="page-item">
								<a class="page-link" href="/product/list/?page=@(i+1)">@(i+1)</a>
							</li>
						}
					}
				}
			</ul>
		</nav>
	</div>
</div>